### ISSUE TITLE
Производитель - Добавить контакт

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#106]
![image](https://user-images.githubusercontent.com/3854363/27129469-1ddec788-510b-11e7-8fb7-e689844c53a7.png)
Переименовать надписи:

- Создать новый OrganizationContact - Создать новый контакт
- Name - ФИО контакта
- Job title - Должность
- Additional email - Дополнительный Email
- Telephones - Убрать
- 0 - убрать

- В форме телефон: 
 Name - Наименование (рабочий, домашний, другое)
Phone number - Номер телефона в формате +Код-страны Код-оператора Номер
Extension number - Добавочный номер

**Comment by crashiura** [comment]
Сделано:
https://github.com/otrada-a/api/pull/117
**Не сделано
Telephones - Убрать
0 - убрать**

**Comment by icechel** [comment]
![image](https://user-images.githubusercontent.com/3854363/27184678-81c440f8-51eb-11e7-8203-cbf7d8a0f232.png)

Тут вместо 
ФИО контакта - Наименование (рабочий, домашний, другое)
entity.telephone.extensionNumber - Добавочный номер

**Comment by grachevko** [comment]
исправлено https://github.com/otrada-a/api/commit/b89668b3c923e894a5f0167322620c5ddfc97b1f

**Comment by icechel** [comment]
Не сделано
Telephones - Убрать
0 - убрать

**Comment by grachevko** [comment]
Исправлено https://github.com/otrada-a/api/pull/199
