### ISSUE TITLE
Security: Не разрешать аутентификацию в админке, если у пользователя нет ROLE_EMPLOYEE

### ISSUE THREAD

**Issue by grachevko** [otrada-a/api#181]

**Comment by vlastv** [comment]
Не разрешать не получится скорее всего.

Возможно можно использовать [access_denied_url](https://symfony.com/doc/current/reference/configuration/security.html) для отправки на спец. страницу

**Comment by grachevko** [comment]
access_denied_url будет работать и для пользователя у которого есть `ROLE_EMPLOYEE`, но каким то образом попавшего на страницу, к которому у него нет доступа. Его должно отправить либо назад по реферу, либо на главную страницу с flash сообщением об отсутствии доступа.
А для тех у кого нет `ROLE_EMPLOYEE` нужно прервать авторизацию, и уже выкинуть на эту спец страницу.

**Comment by vlastv** [comment]
Есть access_denied_handler можно там проверить права доступа, и разлогинить или кинуть флеш.

**Comment by grachevko** [comment]
Да, похоже это подходящее место
