### ISSUE TITLE
Товары - Список

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#190]
1. Переименовать: Идентификатор товарной позиции (артикул) - Артикул
2. Переименовать: Номер производителя- Артикул производителя
3. Убрать столбец - Описание, CreatedAt
4. Добавить столбец со списокм категорий

**Comment by vlastv** [comment]
Если добавить столбец со списком категорий, будет тяжело пользоваться списком. Так как у каждого товара: может быть больше одной категории каталога, что заставит увеличиваться таблицу.

Какую проблему должен решить вывод списка категорий?

**Comment by icechel** [comment]
Таблица не должна увеличиваться. Достаточно просто вывести рубрики к которым привязан товар.
В дальнейшем необходимо решить проблему фильтрации списка товаров по определённой рубрике.

**Comment by icechel** [comment]
Надо добавить ещё главную категорию в список

**Comment by grachevko** [comment]
@icechel создавай другую задачу, эта задача выполнена.
