### ISSUE TITLE
Товар - Просмотр. Добавить список рубрик

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#191]

**Comment by vlastv** [comment]
@icechel задача не ясна

**Comment by icechel** [comment]
Пример: https://admin.mebel-price.net/?action=show&entity=Product&menuIndex=2&submenuIndex=-1&sortField=id&sortDirection=DESC&page=1&referer=%252F%253Faction%253Dlist%2526entity%253DProduct%2526menuIndex%253D2%2526submenuIndex%253D-1%2526sortField%253Did%2526sortDirection%253DDESC%2526page%253D1&id=4

Перед блоком - Свойства добавить блок - Категории.
в нем отображать выбранные рубрики и их родителей в виде дерева.
