### ISSUE TITLE
Продавцы - Создание. При создании нового - ошибка 500. 

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#207]

**Comment by vlastv** [comment]
Продавцы тоже должны иметь артикулы?

**Comment by icechel** [comment]
Да. Такие-же, как и у производителей

**Comment by vlastv** [comment]
Нумерация должна продолжаться, или для продавцов нумерация начинается с 1?

**Comment by icechel** [comment]
Для продавцов код отличается. между страной и числом добавляется буква S.
Пример: RU.S.1 - нумерация отдельная.
