### ISSUE TITLE
Справочник видов материалов

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#250]
Создать отдельный раздел - Виды материалов. Доступ только администратору системы.

**Comment by grachevko** [comment]
Типы листьев дерева:
1. Вид материалов (Материал обивки, фасад), поля: Названия
2. Категория (ценовая), поля: Название, добавочная цена
3. Название коллекции, поля: Название коллекции, вид материала, добавочная цена
4. Разцветка, поля: Название, артикул (не обязательное), фотография.
