### ISSUE TITLE
Продавец - добавить поля ИНН и КПП необязательные

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#308]
ИНН + КПП - https://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&cad=rja&uact=8&ved=0ahUKEwic8oru3I_VAhViJJoKHU2EAmkQFghvMAQ&url=https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%2598%25D0%25B4%25D0%25B5%25D0%25BD%25D1%2582%25D0%25B8%25D1%2584%25D0%25B8%25D0%25BA%25D0%25B0%25D1%2586%25D0%25B8%25D0%25BE%25D0%25BD%25D0%25BD%25D1%258B%25D0%25B9_%25D0%25BD%25D0%25BE%25D0%25BC%25D0%25B5%25D1%2580_%25D0%25BD%25D0%25B0%25D0%25BB%25D0%25BE%25D0%25B3%25D0%25BE%25D0%25BF%25D0%25BB%25D0%25B0%25D1%2582%25D0%25B5%25D0%25BB%25D1%258C%25D1%2589%25D0%25B8%25D0%25BA%25D0%25B0&usg=AFQjCNHKSqrqv36iOx0QCCeWLsJsOG7Zvg

**Comment by vlastv** [comment]
@grachevko  @icechel  что сделать надо в итоге?

**Comment by icechel** [comment]
Пока не делаем.

**Comment by grachevko** [comment]
@icechel для "Пока не делаем." есть лейбл `deffered`

**Comment by icechel** [comment]
В CRM всё должно быть
