### ISSUE TITLE
Разграничение прав.

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#437]
- [ ] Добавить отдельные роли для товара: Добавление, Редактирование, Просмотр, Публикация, Снятие с публикации
- [ ] Добавить отдельные роли для продавца: Добавление, Редактирование, Просмотр, Публикация, Снятие с публикации
- [ ] Добавить отдельные роли для производителя: Добавление, Редактирование, Просмотр, Публикация, Снятие с публикации, Добавление справочника и всех его подсущностей, Редактирование справочника и всех его подсущностей

**Comment by grachevko** [comment]
`ROLE_<entity>_MENU` - используется для показа раздела в навигации. Скрыта из списков ролей на страницах редактирования пользователей и групп. 

`ROLE_<entity>_SHOW` - Доступ к `show`/`list` action всех записей. Наследует `MENU`.

`ROLE_<entity>_NEW` - Доступ к созданию. Просмотр доступен только для своих записей. Редактировать может только свои и только если они ещё ни разу не были опубликованы. Наследует `MENU`.

`ROLE_<entity>_EDIT` - Может всё, наследует `SHOW` и `NEW`.
