### ISSUE TITLE
Статьи. GraphQL. Сделать вывод статей по рубрикам.

### ISSUE THREAD

**Issue by icechel** [otrada-a/api#505]

**Comment by crashiura** [comment]
{
	articles(category:3,tag:1){
  edges {
    node {
      id
      headline
      preview
      tags {
        name
      }
      category {
        name
      }
    }
  }
	}
}

**Comment by crashiura** [comment]
`{
	articles(category:3,tag:1){
  edges {
    node {
      id
      headline
      preview
      tags {
        name
      }
      category {
        name
      }
    }
  }
	}
}`

**Comment by crashiura** [comment]
> 
{
	articles(category:3,tag:1){
  edges {
    node {
      id
      headline
      preview
      tags {
        name
      }
      category {
        name
      }
    }
  }
	}
}
>

**Comment by crashiura** [comment]
```
{
	articles(category:3,tag:1){
  edges {
    node {
      id
      headline
      preview
      tags {
        name
      }
      category {
        name
      }
    }
  }
	}
}
```
