### ISSUE TITLE
Дефекты в разделе Каталог товаров - Поиск

### ISSUE THREAD

**Issue by dsemyonov** [otrada-a/api#595]
1. Жилая мебель ->  Диваны прямые -> Диваны угловые -> Диваны прямые -> Товары перестают отображаться.
2. Жилая мебель ->  Кресла -> Диваны угловые -> Кресла -> Товары дублируются.
3. Жилая мебель -> Открыть на редактирование -> В Описании товара не переведенное название item.delivery time.
4. Нет перехода на раздел Поиск.
5. Жилая мебель -> Обрезанный заголовок Стиль.
6. Жилая мебель -> Меняем значения в разделе Базовая цена -> Переходим в раздел Диваны прямые -> Фильтр по цене не применился.
7. Жилая мебель -> Диваны угловые -> Меняем значения в разделе Базовая цена -> Страница зависает.

**Comment by rchesnokov** [comment]
Исправлено в http://jira.mebel-price.net:8080/browse/FP-50
