### ISSUE TITLE
Ограничения для ввода справочника материалов

### ISSUE THREAD

**Issue by grachevko** [otrada-a/api#610]
Добавить роли для создания справочника материалов:
 - `ROLE_MATERIAL_NEW`
 - `ROLE_MATERIAL_SHOW`
 - `ROLE_MATERIAL_EDIT`.

Добавить в `Material/Directory` поля:
 - `createdBy`
 - `approvedAt`
 - `approvedBy`

Владелец роли `ROLE_MATERIAL_NEW`: 
 - Имеет возможность создать справочник материалов
 - В списке справочников видит только те что создал сам

Созданный справочник пользователем с ролью `ROLE_MATERIAL_NEW` может быть активирован/принят пользователем с ролью `ROLE_MATERIAL_EDIT`.
Если справочник создаётся пользователем с ролью `ROLE_MATERIAL_EDIT`, поля `approvedAt` и `approvedBy` заполняются сразу. В поле `approvedBy` записывается создатель справочника.

**Comment by dsemyonov** [comment]
Редактирование статей
material_show.label
material_edit.label
material_new.label

**Comment by dsemyonov** [comment]
Просмотр товаров
Создание товаров
Редактирование товаров

**Comment by dsemyonov** [comment]
1. Пользователи -> Создать -> Не переведенные роли material_show.label\material_edit.label\material_new.label
2. У ролей material_show.label и material_edit.label, кроме Справочник материалов отображается так же категория Производители.
3. У роли  material_new.label не отображается категория  Справочник материалов (нет возможности создать новый справочник)

**Comment by dmikhinev** [comment]
1. fixed
2. имеется ввиду создание справочника материалов определенного производителя. именно для этого такому пользователю нужна возможность просмотра производителя

**Comment by dsemyonov** [comment]
4. Заходим как пользователь с ролью ROLE_MATERIAL_EDIT -> Справочник материалов -> Создать -> Ошибка -  "Запрашиваемое действие запрещено для этого элемента."

**Comment by dsemyonov** [comment]
5. Заходим как пользователь с ролью ROLE_MATERIAL_SHOW -> Производители -> Выбрать производителя -> Справочник материалов -> Открыть справочник на просмотр -> Ошибка - "Запрашиваемое действие запрещено для этого элемента."

**Comment by dsemyonov** [comment]
Костя, я правильно понимаю роли?

Владелец роли ROLE_MATERIAL_NEW:

	Имеет возможность создать справочник материалов
	В списке справочников видит только те что создал сам
	Может редактировать справочники, которые создал
	Не может удалять справочники
	Не может активировать справочники

Владелец роли ROLE_MATERIAL_SHOW:

	Имеет возможность просматривать справочники материалов
	Не может редактировать, удалять и активировать справочники

Владелец роли ROLE_MATERIAL_EDIT:

	Имеет возможность создать справочник материалов
	В списке справочников видит все справочники
	Может редактировать справочники
	Может удалять справочники
	Может активировать справочники

**Comment by dmikhinev** [comment]
пофиксил проверку ролей

**Comment by dmikhinev** [comment]
выпилил ROLE_MATERIAL_SHOW за ненадобностью

**Comment by dsemyonov** [comment]
Поправка, роль ROLE_MATERIAL_NEW может удалять справочники,  которые создал до момента их активации

**Comment by dmikhinev** [comment]
вернул ROLE_MATERIAL_SHOW. должно быть готово

**Comment by dsemyonov** [comment]
1. Заходим под ролью ROLE_MATERIAL_SHOW -> нет разделов "Справочник материалов", "Производители".

**Comment by dsemyonov** [comment]
Все ОК

**Comment by grachevko** [comment]
https://github.com/otrada-a/api/pull/612
