### ISSUE TITLE
Ошибка при удалении продавца у которого есть производитель

### ISSUE THREAD

**Issue by dsemyonov** [otrada-a/api#705]
**_Шаги воспроизведения_**
1. Открыть вкладку Продавцы.
2. Удалить продавца у которого есть производитель.

**_Ожидаемый результат_**
Удаление продавца.

**_Фактический результат_**
Ошибка - Элемент не может быть удалён, потому что другой элемент зависит от него.
![screenshot from 2017-10-26 18-56-10](https://user-images.githubusercontent.com/31724630/32063255-5bd8a3d2-ba7f-11e7-9302-e5c955f74939.png)

**Comment by crashiura** [comment]
не актуально, перепроверить надо, у меня все ок, я это фиксил.

**Comment by dsemyonov** [comment]
Все ОК
